src/test/java/com/axibase/tsd/api/model/sql/ColumnMetaData.java
src/test/java/com/axibase/tsd/api/model/sql/StringTable.java
src/test/java/com/axibase/tsd/api/model/sql/StringTableDeserializer.java

-  added new column class, that the only determines a table column
-  this class contain meta data about every column
-  StringTable  migrated to  map structure.

migrate to map structure of table

---

src/test/java/com/axibase/tsd/api/method/sql/operators/SqlNotEqualsOperator.java
src/test/java/com/axibase/tsd/api/model/series/Series.java
src/test/java/com/axibase/tsd/api/model/sql/StringTable.java

- `setTags` to Series class
-  `filterRows` to StringTable class, that accepts args form arguments

SQL: Not equals operator new syntax tests

---

src/test/java/com/axibase/tsd/api/method/sql/date_format/SqlTimezoneFormatTests.java

SQL: timezone additional test

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/where/SqlEntityTags.java

SQL: entity tags in where clause

---

src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectMetricTagsTest.java

- added tests for dash in tag's name

SQL: Metric tags, additional case sensitivity and `dash-name`  tests(squashed)

---

src/test/java/com/axibase/tsd/api/method/replacementtable/ReplacementTableMethod.java
src/test/java/com/axibase/tsd/api/method/sql/operator/SqlLookupFunctionTest.java
src/test/java/com/axibase/tsd/api/model/replacementtable/ReplacementTable.java
src/test/java/com/axibase/tsd/api/util/Registry.java

SQL: LOOKUP function to perform a value replacement #3555 + LOOKUP function doesn't support tags, entity.tags, metric.tags fields #3769

---

src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTest.java
src/test/java/com/axibase/tsd/api/model/series/Sample.java
src/test/java/com/axibase/tsd/api/model/series/Series.java
src/test/java/com/axibase/tsd/api/model/series/ValueDeserializer.java
src/test/java/com/axibase/tsd/api/util/Mocks.java

Bugfix: custom value deserializer and text samples mocks

---

src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/DateFormatInsideHavingClauseTest.java

added tests for #3893
Don't be confused by the name of this request.
Main problem of that bug was about HAVING clause not accepting a date_format function inside.

SQL: delta aggregator returns incorrect values when dates are filtered #3893

---

src/test/java/com/axibase/tsd/api/method/sql/clause/groupby/GroupByPeriodInLeapYears.java

added tests for #3825
Problem wasn't in interpolation, but in leap year's boundaries measurement.

SQL: extra period row with VALUE interpolation #3825

---

src/test/java/com/axibase/tsd/api/method/sql/clause/select/SelectTagsWithGroupBy.java

SQL: tags.* can't be used in SELECT clause #4013

---

src/test/java/com/axibase/tsd/api/method/sql/clause/orderby/OrderByAggregatedValuesFromMultipleTables.java

added tests for #3840
**DON'T BE CONFUSED BY THE NAME OF THIS PULL REQUEST!**
Name was taken from ticket's name, but the problem of ORDER BY malfunction wasn't connected to column aliases.
The main problem was ordering by column with aggregation function that have parameters from multiple metrics -- like SUM(table1.value + table2.value).

SQL: ORDER BY not applied when using column alias #3840

---

src/test/java/com/axibase/tsd/api/method/sql/function/string/DatetimeTypeTest.java

added tests for #4221 (checked that datetime handled as ISO-timespamp in string functions and time handled as UNIX-timestamp)

SQL: isnull return long for string datatypes #4221

---

src/test/java/com/axibase/tsd/api/method/sql/function/string/CastTest.java

added tests for #3841
Not sure if that's enough, because that problem is kind of sophisticated. Here's a quote of Alexander Tokarev about the bug: 
> в #3841 получилась ошибка при парсинге запроса. в выражении AND CAST(e.tags.cty_code AS number) > 1000  присутствует число  1000
> это число при парсинге ошибочно принималось за аргумент функции period, получалось period(1000 year) в результате

SQL: CAST in WHERE filter changes results #3841

---

src/main/java/com/axibase/tsd/api/method/checks/SeriesCheck.java
src/test/java/com/axibase/tsd/api/method/series/command/BackslashCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/series/command/DoubleBackslashCharEscapeTest.java

Previously disabled tests no longer failing due to fix in #4662

Enabled faliling tests

---

src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTransformationsLimitTest.java

These test should run fervently on atsd revision >= 18538.

Add tests for series query limit. Tickets #4835 and #4836.

---

src/main/java/com/axibase/tsd/api/model/metric/Metric.java
src/test/java/com/axibase/tsd/api/method/series/SeriesSearchTest.java
src/test/java/com/axibase/tsd/api/method/sql/clause/select/SelectAliasSameAsColumnTest.java
src/test/java/com/axibase/tsd/api/method/sql/clause/select/SqlSelectMetricFieldsTest.java

Delete the "timePrecision" metric's field from tests because it is also deleted from the ATSD metric object - ticket #5438.

Delete the "timePrecision" field.

---

src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTest.java

Remove API series query test which checks that the 'period' parameter is specified in the 'aggregate' settings. Now this parameter is optional - ticket #5471.

Remove test which check that period is specified in aggregation.

---

README.md

Removed information on how to rerun tests on same ATSD: too difficult and error-prone. Use fresh containers instead.
Showed that running a special image should be enough to run tests.
Initialize missing environment variables.

Updated API tests running tutorial

---

src/main/java/com/axibase/tsd/api/model/series/query/SeriesQuery.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTransformationsWithoutForecastPermutationsTest.java

Fix SeriesQueryTransformationsWithoutForecastPermutationsTest test.
Parallel testing threads modify and test the same query object.
Fix that by cloning query for each test case.

Test permutations of series transformations - fix data race bug.

---

src/test/java/com/axibase/tsd/api/method/tokens/TokenMessageTest.java

Seems that previous implementation of the message stats service manually sets queried alignment to START_TIME. Current implementation uses default calendar alignment, and the test fails. So I set START_TIME alignment in the test to fix this discrepancy.

Fix TokenMessageTest.testStatsMethod.

---

pom.xml
src/main/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/main/java/com/axibase/tsd/api/util/JsonParsingException.java
src/test/java/com/axibase/tsd/api/method/series/trade/TradeSideTest.java

More careful check that response is a valid json string. Additional tests for trade API queries with different required sides.
ATSD may send something like the following in response to API series query:
```
[{"metric":"cpu_usage"}]DATA_API_SERIES_QUERY_PROCESSING_ERRORcom.axibase.Class: Exception
```
That happence if ATSD produces an exception after response was partially written.
Current tests do not notice what json is broken and just ignore
the `DATA_API_SERIES_QUERY_PROCESSING_ERRORcom.axibase.Class: Exception` string.
So I've added another json parsing library and additional check that json is well-formed.
Some of tests started to fail after this additional check, due to unnoticed bug in ATSD,
which is fixed in https://github.com/axibase/tsd/pull/1015 (not merged in the master).

Additional check that response is a valid json string. More test cases for trade API queries.

---

src/main/java/com/axibase/tsd/api/method/checks/Check.java
src/test/java/com/axibase/tsd/api/method/message/MessageTest.java

In the message tests, we usually insert a message and then query it.
Based on the response code we may repeat the query, in order to get ATSD more time
to process the message. The response code is not a too reliable way to determine that the message is still not processed by ATSD. (I have changed message processing, ATSD starts to return another code during message processing time, and tests fail.)
This PR should mitigate this issue in the case when the message has a unique entity, and ATSD needs time to create the entity. In this case, we may (optionally) check that entity was created before checking the message itself.

API message tests: check that message entity is created before check the message itself.

---

src/main/java/com/axibase/tsd/api/model/Period.java
src/main/java/com/axibase/tsd/api/model/series/query/SeriesQuery.java
src/main/java/com/axibase/tsd/api/util/Util.java
src/test/java/com/axibase/tsd/api/method/financial/InstrumentSearchBase.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryForecastAutoAggregateTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryReadStoredForecastTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTagExpressionFilterTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryWildcardTest.java
src/test/java/com/axibase/tsd/api/method/series/trade/SyntheticDataProvider.java
src/test/java/com/axibase/tsd/api/method/series/trade/TradeSideTest.java

Change `SeriesQuery.tags` type from `Map<String, String>` to `Map<String, List<String>>` to allow multiple values for a tag in API series query.

Support multiple values for a tag in series query.

---

src/main/java/com/axibase/tsd/api/model/financial/Trade.java
src/test/java/com/axibase/tsd/api/method/series/trade/GroupingTest.java
src/test/java/com/axibase/tsd/api/util/TimeUtil.java

Implement method `GroupingTest.testDetailGrouping()` which tests a query similar with:
```
[{
"entity": "aaa_[bbb]",
"metric": "trade_price",
"group": {"type": "DETAIL"},
"startDate": "2021-02-25T07:09:55.000Z",
"endDate": "2021-02-25T07:10:00.000Z",
"timeFormat": "iso"
}]
```

Test trade API series query with "detail" group type.

---

src/main/java/com/axibase/tsd/api/model/series/Series.java
src/main/java/com/axibase/tsd/api/model/series/query/SeriesQuery.java
src/main/java/com/axibase/tsd/api/model/series/query/transformation/forecast/Forecast.java
src/main/java/com/axibase/tsd/api/model/series/query/transformation/forecast/TimeFilter.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryForecastTimeFilterTest.java
src/test/java/com/axibase/tsd/api/util/TimeUtil.java

Test usage of `TimeFilter` during forecasting. The `timeFilter` setting is one of the `ForecastSettings` fields which allows filter input series samples based on their timestamps and is used to assign timestamps to a forecasted / reconstructed series.

Test ForecastSettings.TimeFilter.

---

src/test/java/com/axibase/tsd/api/method/series/TransformationPermutationsTest.java

Series query transformations test - change test data so that all series in a response is not empty, and check that.
Sasha, could you also merge it, please.

Make test of series transformations more reliable.

---

src/main/java/com/axibase/tsd/api/method/checks/SeriesCheck.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryLimitTest.java

More detailed message in the case when a check of inserted test series fails - print a failed query, expected and actual responses.
Sasha, could you please, merge this.

Change error message in insert series check.

---

src/main/java/com/axibase/tsd/api/method/forecast/ForecastMethod.java
src/main/java/com/axibase/tsd/api/model/series/Series.java
src/main/java/com/axibase/tsd/api/model/series/SeriesMeta.java
src/test/java/com/axibase/tsd/api/method/forecast/ForecastFormTest.java

A Forecast Job /forecast/settings/edit.xhtml
allows to group requested series, calculate a forecast for each group, and store the forecast either
in series table or in forecast table under specified metric.
The test checks, that those forecasts are actually stored in suitable table, and with correct series keys.
Sasha, could you please merge this PR, if you accept it.

Test that forecasts produced by a Forecast Job are correctly stored.

---

src/test/java/com/axibase/tsd/api/method/forecast/ForecastFormTest.java

Turn off `ForecastFormTest` until it will be fixed.

Turn off failed test.

---

src/test/java/com/axibase/tsd/api/method/forecast/ForecastFormTest.java

Set large forecast retention interval to prevent a forecast from immediate deletion. (Retention interval is counted down from test running time.)

Fix ForecastFormTest - set large retention interval.
