axibase/atsd-api-test

src/test/java/com/axibase/tsd/api/Util.java
src/test/java/com/axibase/tsd/api/method/property/PropertyCommandTest.java
src/test/java/com/axibase/tsd/api/method/property/PropertyInsertTest.java
src/test/java/com/axibase/tsd/api/method/property/PropertyMethod.java
src/test/java/com/axibase/tsd/api/method/property/PropertyQueryTest.java

Some tests to check keyTagExpression work

add tests for #2908

---

README.md
src/test/java/com/axibase/tsd/api/Registry.java
src/test/java/com/axibase/tsd/api/method/property/PropertyMethod.java
src/test/java/com/axibase/tsd/api/method/property/PropertyQueryTest.java

limit_field tests

---

pom.xml
src/test/java/com/axibase/tsd/api/method/series/CSVInsertTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesCommandTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesInsertTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/test/java/com/axibase/tsd/api/model/series/SeriesQuery.java

change series method
change Config

refactoring

---

src/test/java/com/axibase/tsd/api/method/compaction/CompactionMethod.java
src/test/java/com/axibase/tsd/api/method/message/MessageCommandTest.java
src/test/java/com/axibase/tsd/api/method/property/PropertyCommandTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesCommandTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesInsertTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/test/java/com/axibase/tsd/api/model/series/Sample.java
src/test/java/com/axibase/tsd/api/model/series/Series.java

sync with master

---

src/test/java/com/axibase/tsd/api/method/sql/SqlExecuteMethod.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseCodesTests.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseHeadersTests.java

Tested :
- response codes
- response headers

Testing API SQL response 

---

src/test/java/com/axibase/tsd/api/method/sql/SqlMethod.java
src/test/java/com/axibase/tsd/api/method/sql/period/interpolation/SqlPeriodInterpolationTests.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseCodesTests.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseHeadersTests.java

*Contains tests that check different interpolation options*

SQL: Period Interpolation tests

---

src/test/java/com/axibase/tsd/api/method/sql/period/align/SqlPeriodAlignTest.java
src/test/java/com/axibase/tsd/api/method/sql/period/filtering/SqlPeriodDataFilteringTest.java

- tests for alignment
- tests for filtering

SQL: test period alignment and filtering

---

src/test/java/com/axibase/tsd/api/method/sql/datatype/SqlNullDataTypeTests.java
src/test/java/com/axibase/tsd/api/model/series/Series.java

- aripthmetical operations tests
- aggreagate operation test

SQL: null data type tests 

---

src/test/java/com/axibase/tsd/api/method/sql/metadata/SqlMetaDataTests.java

- propertyUrl tests
- column datatype tests

SQL: tests metadata fields

---

src/test/java/com/axibase/tsd/api/method/sql/SqlMethod.java

SQL: method migrate to post request

---

src/test/java/com/axibase/tsd/api/Util.java
src/test/java/com/axibase/tsd/api/method/csv/CSVUploadTest.java
src/test/java/com/axibase/tsd/api/method/message/MessageInsertTest.java
src/test/java/com/axibase/tsd/api/method/property/PropertyInsertTest.java
src/test/java/com/axibase/tsd/api/method/series/CSVInsertTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesInsertTest.java
src/test/java/com/axibase/tsd/api/model/property/Property.java
src/test/resources/com/axibase/tsd/api/method/csv/csv_upload/testTimeRangeInISO.csv
src/test/resources/com/axibase/tsd/api/method/csv/csv_upload/testTimeRangeInMS.csv

https://github.com/axibase/atsd-api-test/pull/37

code revised

---

src/test/java/com/axibase/tsd/api/method/message/MessageInsertTest.java
src/test/java/com/axibase/tsd/api/method/message/MessageMethod.java
src/test/java/com/axibase/tsd/api/method/message/MessageQueryTest.java
src/test/java/com/axibase/tsd/api/method/property/PropertyInsertTest.java
src/test/java/com/axibase/tsd/api/method/property/PropertyQueryTimezoneTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesInsertTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTest.java
src/test/java/com/axibase/tsd/api/model/series/SeriesQuery.java

add checks for insert

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/operators/SqlModuloTests.java
src/test/java/com/axibase/tsd/api/model/sql/StringTable.java

SQL: arithmetic modulo tests

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/date_format/SqlTimezoneFormatTests.java
src/test/java/com/axibase/tsd/api/model/sql/StringTable.java

SQL: timezone format

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectAllWithJoinTests.java

SQL: select all from join table

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/operators/SqlIsNullOperator.java

SQL: IS NULL operator tests

---

src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectAllWithJoinTests.java

SQL: additional test for tags.* select

---

src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectMetricTagsTest.java
src/test/java/com/axibase/tsd/api/model/metric/Metric.java

SQL: select metric tags

---

src/test/java/com/axibase/tsd/api/method/sql/datatype/SqlNullDataTypeTest.java

- SQL queries rewrited as SQL standard fixed in #3057 issue

SQL: column and aggregation function in select

---

src/test/java/com/axibase/tsd/api/method/sql/operators/SqlIsNullOperatorTest.java

SQL: updating entity after creation(squashed)

---

src/test/java/com/axibase/tsd/api/method/sql/period/SqlPeriodSyntaxTest.java

SQL: period syntax

---

src/test/java/com/axibase/tsd/api/method/sql/period/extend/SqlPeriodExtendTest.java

SQL: period extend option

---

src/test/java/com/axibase/tsd/api/method/sql/function/math/SqlFunctionMathTest.java

SQL: math functions

---

src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTest.java

Test trying to insert samples every day between 1969 and 2110 with some randomization

API: series query

---

src/test/java/com/axibase/tsd/api/method/sql/select/SqlUnGroupedColumnTest.java

SQL: ungrouped column error

---

src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectAllWithJoinTest.java
src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectMetricTagsTest.java

SQL: bugfix: new select all syntax

---

.travis.yml
src/test/java/com/axibase/tsd/api/method/sql/operators/SqlIsNullNanHandlingTest.java

SQL: IS NULL with NaN values tests

---

src/test/java/com/axibase/tsd/api/method/sql/groupby/SqlGroupByDatetime.java

SQL: group by datetime tests 

---

src/test/java/com/axibase/tsd/api/method/entitygroup/EntityGroupsMethod.java
src/test/java/com/axibase/tsd/api/method/sql/where/SqlEntityGroupsWhereClauseTest.java
src/test/java/com/axibase/tsd/api/model/entitygroup/EntityGroup.java

SQL: entity in group clause

---

src/test/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/test/java/com/axibase/tsd/api/method/sql/SqlMethod.java
src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/datatype/SqlNullDataTypeTest.java
src/test/java/com/axibase/tsd/api/method/sql/date_format/SqlTimezoneFormatTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/math/SqlFunctionMathTest.java
src/test/java/com/axibase/tsd/api/method/sql/groupby/SqlGroupByDatetime.java
src/test/java/com/axibase/tsd/api/method/sql/metadata/SqlMetaDataTest.java
src/test/java/com/axibase/tsd/api/method/sql/operators/SqlIsNullNanHandlingTest.java
src/test/java/com/axibase/tsd/api/method/sql/operators/SqlIsNullOperatorTest.java
src/test/java/com/axibase/tsd/api/method/sql/operators/SqlModuloTest.java
src/test/java/com/axibase/tsd/api/method/sql/operators/SqlNotEqualsOperatorTest.java
src/test/java/com/axibase/tsd/api/method/sql/period/SqlPeriodSyntaxTest.java
src/test/java/com/axibase/tsd/api/method/sql/period/align/SqlPeriodAlignTest.java
src/test/java/com/axibase/tsd/api/method/sql/period/extend/SqlPeriodExtendTest.java
src/test/java/com/axibase/tsd/api/method/sql/period/filtering/SqlPeriodDataFilteringTest.java
src/test/java/com/axibase/tsd/api/method/sql/period/interpolation/SqlPeriodInterpolationTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseCodesTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseHeadersTest.java
src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectAllWithJoinTest.java
src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectMetricTagsTest.java
src/test/java/com/axibase/tsd/api/method/sql/select/SqlUnGroupedColumnTest.java
src/test/java/com/axibase/tsd/api/method/sql/where/SqlEntityGroupsWhereClauseTest.java
src/test/java/com/axibase/tsd/api/method/sql/where/SqlEntityTagsTest.java
src/test/java/com/axibase/tsd/api/model/series/Series.java
src/test/java/com/axibase/tsd/api/model/series/SeriesQuery.java
src/test/java/com/axibase/tsd/api/model/sql/StringTable.java

Refactoring: extension of Series Method 

---

src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlTagNameWithDoubleQuotationTest.java

SQL: tags' name column  with double quotes

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/orderby/SqlOrderByAlphabeticalTest.java
src/test/java/com/axibase/tsd/api/model/series/Series.java
src/test/java/com/axibase/tsd/api/model/sql/StringTable.java

SQL: alphabetical order

---

src/test/java/com/axibase/tsd/api/method/sql/select/SqlSelectMetricTagsTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlTableAliasTest.java

SQL: table aliases tests

---

src/test/java/com/axibase/tsd/api/method/sql/clause/select/SqlSelectEntityTagsTest.java

SQL : select entity tags tests

---

src/test/java/com/axibase/tsd/api/method/sql/examples/aggregation/SqlExampleAggregateMaxValueTimeTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/aggregation/SqlExampleAvgValueTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/aggregation/SqlExampleCounterAggregatorTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/aggregation/SqlExamplePerPeriodTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/aggregation/SqlExamplePercentilesTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/aggregation/SqlExampleSlidingWindowsTest.java

SQL: aggregation examples' tests

---

.travis.yml
src/test/java/com/axibase/tsd/api/method/sql/operator/SqlModuloTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseHeadersTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlNullDataTypeTest.java

SQL: ambiguously columns in JOIN queries

---

src/test/java/com/axibase/tsd/api/method/sql/function/math/SqlFunctionMathTest.java
src/test/java/com/axibase/tsd/api/method/sql/operator/SqlOperatorIsNullWithMathFunctionsTest.java

SQL: IS null operator with math functions

---

src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/SqlFunctionDateFormatWithMaxMinValueTimeTest.java

SQL: date_format doesn't process max_value_time as argument tests

---

src/test/java/com/axibase/tsd/api/method/sql/examples/select/SqlSelectFromAtsdSeriesTest.java

SQL: select form atsd_series example tests

---

src/test/java/com/axibase/tsd/api/method/sql/clause/orderby/SqlClauseOrderByAggregatedColumnAliasTest.java

SQL: order by alias of aggregated column

---

src/test/java/com/axibase/tsd/api/method/sql/SqlMethod.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxCommentsTest.java

SQL: comments support

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/clause/select/SqlSelectAllTagsOrderTest.java

SQL: tags column names order tests

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxAmbiguouslyColumnsTest.java

SQL: ambiguous columns tests 

---

src/test/java/com/axibase/tsd/api/Util.java
src/test/java/com/axibase/tsd/api/method/sql/examples/aggregation/SqlExampleAggregateMaxValueTimeTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/SqlTimezoneFormatTest.java

SQL: date_format tests fixed

---

src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxDelimiterTest.java

SQL: delimiter tests

---

src/test/java/com/axibase/tsd/api/method/sql/clause/limit/SqlClauseLimitOffsetTest.java

SQL: offset tests

---

src/test/java/com/axibase/tsd/api/method/sql/operator/SqlModuloTest.java

SQL: hotfix

---

src/test/java/com/axibase/tsd/api/method/sql/examples/select/SqlExampleComputedColumnsTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxComputedColumnsInClausesTest.java

SQL: computed columns  tests

---

src/test/java/com/axibase/tsd/api/method/sql/examples/select/SqlExampleQuoteEscapingTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxQuotesEscapingTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlTagNameWithDoubleQuotationTest.java

SQL: quotes escaping in collection name

---

src/test/java/com/axibase/tsd/api/method/sql/operator/SqlOperatorComparisonStringTest.java

SQL: comparison test

---

src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxUnknownAliasTest.java

SQL: unknown alias tests

---

src/test/java/com/axibase/tsd/api/method/sql/SqlMethod.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlLimitParamTest.java

SQL: requsest limit with SQL limit

---

src/test/java/com/axibase/tsd/api/method/sql/clause/where/SqlClauseWhereWithLimitDoubleTest.java

SQL: NPE if both comparison with float value in WHERE and LIMIT are used

---

src/test/java/com/axibase/tsd/api/method/sql/examples/ordering/SqlExampleOrderByCollationTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/ordering/SqlExampleOrderByMultipleColumnsTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/ordering/SqlExampleOrderByTimeTest.java
src/test/java/com/axibase/tsd/api/method/sql/examples/ordering/SqlExampleOrderByValueTest.java

SQL: ordering examples tests

---

src/test/java/com/axibase/tsd/api/method/sql/operator/SqlOperatorNotEqualsWithNullTest.java

SQL: series tag NULL condition

---

src/test/java/com/axibase/tsd/api/Util.java
src/test/java/com/axibase/tsd/api/method/sql/function/period/align/SqlPeriodDayAlignTest.java

SQL: day align bugfix

---

src/test/java/com/axibase/tsd/api/method/BaseMethod.java
src/test/java/com/axibase/tsd/api/method/alert/AlertHistoryQueryTest.java
src/test/java/com/axibase/tsd/api/method/alert/AlertMethod.java

no ticket for this issue.
relative to #2981

fix alerthistory tests

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java

SQL: fixed tests

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/clause/join/SqlClauseJoinValueOrderTest.java

SQL join order by value tests

---

src/test/java/com/axibase/tsd/api/method/BaseMethod.java
src/test/java/com/axibase/tsd/api/method/alert/AlertHistoryQueryTest.java
src/test/java/com/axibase/tsd/api/method/entity/EntityCommandTest.java
src/test/java/com/axibase/tsd/api/method/message/MessageInsertTest.java
src/test/java/com/axibase/tsd/api/method/message/MessageMethod.java
src/test/java/com/axibase/tsd/api/method/message/command/BackslashNoEscapeTest.java
src/test/java/com/axibase/tsd/api/method/message/command/DQuoteCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/message/command/DoubleBackslashNoEscapeTest.java
src/test/java/com/axibase/tsd/api/method/message/command/EqualCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/message/command/LengthTest.java
src/test/java/com/axibase/tsd/api/method/property/PropertyMethod.java
src/test/java/com/axibase/tsd/api/method/property/command/BackslashCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/property/command/DQuoteCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/property/command/DoubleBackslashCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/property/command/EqualCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/property/command/LengthTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/test/java/com/axibase/tsd/api/method/series/command/BackslashCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/series/command/DQuoteCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/series/command/DoubleBackslashCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/series/command/EqualCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/series/command/LengthTest.java
src/test/java/com/axibase/tsd/api/model/message/Message.java
src/test/java/com/axibase/tsd/api/model/series/Sample.java

it's ok for 1 series command test fail. Relative issue is #3361

add escape char tests

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/SqlFunctionDateFormatTimeExpressionTest.java

SQL: date_format aripthmetic expression

---

src/test/java/com/axibase/tsd/api/Util.java
src/test/java/com/axibase/tsd/api/method/BaseMethod.java
src/test/java/com/axibase/tsd/api/method/alert/AlertHistoryQueryTest.java
src/test/java/com/axibase/tsd/api/method/alert/AlertMethod.java
src/test/java/com/axibase/tsd/api/method/alert/AlertQueryAcknowledgedTest.java
src/test/java/com/axibase/tsd/api/method/alert/AlertQueryTest.java
src/test/java/com/axibase/tsd/api/method/alert/AlertTest.java
src/test/java/com/axibase/tsd/api/method/sql/clause/with/SqlClauseWithLastTimeTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxUnknownAliasTest.java

SQL:last_time expression WITH clause  

---

src/test/java/com/axibase/tsd/api/method/BaseMethod.java

Client: increased socket timeout

---

src/test/java/com/axibase/tsd/api/TestNameGenerator.java
src/test/java/com/axibase/tsd/api/Util.java

Feature: TestNameGenerator

---

src/test/java/com/axibase/tsd/api/listeners/RetryAnalyzer.java
src/test/java/com/axibase/tsd/api/method/alert/AlertHistoryQueryTest.java

SQL: Retry Analyzer for some test

---

src/test/java/com/axibase/tsd/api/TestNameGenerator.java
src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/clause/orderby/LimitTest.java

SQL: order limit tests 

---

src/test/java/com/axibase/tsd/api/TestNameGenerator.java
src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/interpolate/ApplyTest.java
src/test/java/com/axibase/tsd/api/model/Interval.java
src/test/java/com/axibase/tsd/api/model/sql/function/interpolate/Alignment.java
src/test/java/com/axibase/tsd/api/model/sql/function/interpolate/Boundary.java
src/test/java/com/axibase/tsd/api/model/sql/function/interpolate/Fill.java
src/test/java/com/axibase/tsd/api/model/sql/function/interpolate/InterpolateFunction.java

SQL: interpolate apply test

---

src/test/java/com/axibase/tsd/api/method/alert/AlertHistoryQueryTest.java

SQL: disable AlertHistoryQuery tests

---

src/test/java/com/axibase/tsd/api/method/sql/function/interpolate/ApplyTest.java

SQL: interpolate series with only NaN values

---

src/test/java/com/axibase/tsd/api/method/metric/MetricCommandTest.java
src/test/java/com/axibase/tsd/api/method/metric/MetricCreateOrReplaceTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/AutoTimeZone.java
src/test/java/com/axibase/tsd/api/model/command/MetricCommand.java
src/test/java/com/axibase/tsd/api/model/metric/Metric.java

Feature: added new metric's fileds

---

src/test/java/com/axibase/tsd/api/Util.java
src/test/java/com/axibase/tsd/api/method/entity/EntityCommandTest.java
src/test/java/com/axibase/tsd/api/method/entity/EntityCreateOrReplaceTest.java
src/test/java/com/axibase/tsd/api/method/entity/EntityGetTest.java
src/test/java/com/axibase/tsd/api/method/entity/EntityMethod.java
src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/AutoTimeZoneTest.java
src/test/java/com/axibase/tsd/api/model/command/entity/EntityCommand.java
src/test/java/com/axibase/tsd/api/model/common/InterpolationMode.java
src/test/java/com/axibase/tsd/api/model/entity/Entity.java
src/test/java/com/axibase/tsd/api/transport/tcp/TCPSender.java

Feature: Added entity command, updated entity Model

---

src/test/java/com/axibase/tsd/api/Util.java
src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/AutoTimeZone.java
src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/AutoTimeZoneTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ConcatTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/IsNullTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LengthTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LocateTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LowerTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ReplaceTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/SubStrTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/UpperTest.java

SQL: added AutoTimeZone tests

---

src/test/java/com/axibase/tsd/api/AtsdErrorMessage.java
src/test/java/com/axibase/tsd/api/CommonAssertions.java
src/test/java/com/axibase/tsd/api/method/BaseMethod.java
src/test/java/com/axibase/tsd/api/method/entity/EntityCreateOrReplaceTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesInsertTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseCodesTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlApiResponseHeadersTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlMetaDataTest.java

Hotfix: fix crashed tests, disabled tests that related with migration to spring4

---

src/test/java/com/axibase/tsd/api/method/sql/clause/limit/LimitAggregationFunctionTest.java

SQL: COUNT and LIMIT tests

---

src/test/java/com/axibase/tsd/api/method/sql/clause/orderby/LimitTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/interpolate/ApplyTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ConcatTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/IsNullTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LengthTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LocateTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LowerTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ReplaceTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/SubStrTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/UpperTest.java

Hotfix: disable parallel for data providers

---

src/test/java/com/axibase/tsd/api/method/sql/clause/select/SqlUnGroupedColumnTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/period/interpolation/SqlPeriodInterpolationTest.java
src/test/java/com/axibase/tsd/api/util/ErrorTemplate.java

Hotfix: Fix tests with last atsd changes

---

src/test/java/com/axibase/tsd/api/method/sql/clause/limit/SqlClauseLimitOffsetTest.java

SQL: fix error messages

---

src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlParseTimeCheck.java

SQL: slow summation query #3711

---

src/test/java/com/axibase/tsd/api/method/sql/clause/join/SqlClauseJoinUsingEntity.java

SQL: JOIN USING entity #3741

---

src/test/java/com/axibase/tsd/api/method/sql/function/period/extend/SqlPeriodExtendTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/CommonData.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/IsNullTest.java

SQL: ISNULL empty string handling 

---

src/test/java/com/axibase/tsd/api/method/series/SeriesInsertTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTest.java
src/test/java/com/axibase/tsd/api/model/series/Sample.java
src/test/java/com/axibase/tsd/api/model/series/SampleVersion.java
src/test/java/com/axibase/tsd/api/model/series/Series.java
src/test/java/com/axibase/tsd/api/model/series/SeriesQuery.java

Test of series insertion to versioned metric with text field keeps versioning

Data API: Text field versioning

---

src/test/java/com/axibase/tsd/api/method/sql/function/math/SqlFunctionMathAbs.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlParseTimeTest.java

SQL: Math function ABS does not accept 2nd aggregate expression #3738

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/CastTest.java

added tests for #3661
moved to sql.function.string
renamed to CastTest
edited 1 line in SqlTest

SQL: CAST function #3661

---

src/test/java/com/axibase/tsd/api/method/sql/function/aggregate/AverageFunction.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/CommonData.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ConcatTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/IsNullTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LengthTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LocateTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LowerTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ReplaceTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/SubStrTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/UpperTest.java

SQL: string functions result tests #2920

---

src/test/java/com/axibase/tsd/api/method/sql/SqlMethod.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlDataTypeInferenceTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlDataTypeTest.java

Added test for data type inference (metadata) #3773

SQL: data type inference test #3773

---

src/test/java/com/axibase/tsd/api/method/sql/clause/join/JoinWithTagOrEntityFilter.java
src/test/java/com/axibase/tsd/api/method/sql/clause/join/SqlClauseJoinWithTagFilter.java

SQL: tag filter for the 2nd table removes all rows in JOIN #3756

---

src/test/java/com/axibase/tsd/api/method/sql/function/string/CommonData.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ConcatTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/IsNullTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LengthTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LocateTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/LowerTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/ReplaceTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/SubStrTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/UpperTest.java

SQL: CONCAT for numbers #3768

---

src/test/java/com/axibase/tsd/api/method/sql/clause/groupby/GroupByEntityTag.java

SQL: group by entity tag #3795

---

src/test/java/com/axibase/tsd/api/method/sql/clause/groupby/GroupByCaseExpression.java

SQL: Invalid grouping for column "time" #3892

---

src/test/java/com/axibase/tsd/api/method/sql/clause/join/JoinWithTags.java

SQL: Malformed tag names JOIN query #3873

---

src/test/java/com/axibase/tsd/api/method/sql/keyword/KeywordCaseSensitivityTest.java

added tests for #3843
TESTS FAIL, BECAUSE OF UNRESOLVED ISSUE

SQL: keywords are case-sensitive  #3843

---

pom.xml
src/main/java/com/axibase/tsd/api/method/checks/SeriesCheck.java
src/main/java/com/axibase/tsd/api/model/command/EntityCommand.java
src/main/java/com/axibase/tsd/api/model/command/FieldFormat.java
src/main/java/com/axibase/tsd/api/model/command/SeriesCommand.java
src/main/java/com/axibase/tsd/api/model/series/Series.java
src/main/java/com/axibase/tsd/api/transport/tcp/TCPSender.java
src/test/java/com/axibase/tsd/api/transport/tcp/TCPSenderTest.java
src/test/java/com/axibase/tsd/api/util/CommonAssertions.java
src/test/java/com/axibase/tsd/api/util/Mocks.java
src/test/java/com/axibase/tsd/api/util/TestNameGenerator.java

Dev: Refactored TCP sender

---

src/test/java/com/axibase/tsd/api/method/sql/clause/with/RowNumberBeforeGroupBy.java

SQL: ROW_NUMBER function - support for period #3797

---

src/test/java/com/axibase/tsd/api/method/sql/function/aggregation/AggregationNullValuesTest.java

SQL: NPE in JOIN query when aggregating null values #3880

---

src/test/java/com/axibase/tsd/api/method/sql/clause/groupby/GroupByCaseExpression.java

SQL: NPE in JOIN without a where condition #3912

---

src/test/java/com/axibase/tsd/api/method/sql/function/string/IsNullTest.java

SQL: Error when ISNULL is a part of expression #3844

---

src/test/java/com/axibase/tsd/api/method/sql/response/SqlLargeDataTest.java

SQL: high-cardinility metric: tag encoding error #3890

---

src/main/java/com/axibase/tsd/api/model/series/SeriesQuery.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTest.java

After changes made in issue 3918 (https://nur.axibase.com:41791/redmine/issues/3918) test "testLastSeriesWithText" became invalid

Fixed test passing error

---

.travis.yml
src/main/java/com/axibase/tsd/api/Config.java
src/main/java/com/axibase/tsd/logging/LoggingFilter.java
src/test/resources/client.properties
src/test/resources/logback.xml

[Feature]: add control for checker logs 

---

src/test/java/com/axibase/tsd/api/method/sql/clause/join/OuterJoinMergeTest.java
src/test/java/com/axibase/tsd/api/method/sql/clause/join/SqlJoinWithAggregations.java
src/test/java/com/axibase/tsd/api/method/sql/clause/limit/SqlClauseLimitOffsetTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/aggregation/AggregationNullValuesTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/SqlFunctionDateFormatTimeExpressionTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/period/interpolation/SqlPeriodInterpolationTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/CastTest.java
src/test/java/com/axibase/tsd/api/method/sql/function/string/IsNullTest.java
src/test/java/com/axibase/tsd/api/method/sql/keyword/KeywordCaseSensitivityTest.java
src/test/java/com/axibase/tsd/api/method/sql/operator/SqlIsNullOperatorTest.java
src/test/java/com/axibase/tsd/api/method/sql/operator/SqlOperatorComparisonStringTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxAmbiguouslyColumnsTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxDelimiterTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSyntaxUnknownAliasTest.java
src/test/java/com/axibase/tsd/api/util/ErrorTemplate.java

[Hotfix]fix test related to new changes in atsd

---

src/test/java/com/axibase/tsd/api/method/sql/function/dateformat/DateFormatInsideClausesTest.java

Trying to fix problems with timezones, once again...

Split test data

---

src/test/java/com/axibase/tsd/api/method/sql/keyword/BetweenInsideWhere.java

SQL: BETWEEN keyword failure when used with another conditions #4014

---

src/test/java/com/axibase/tsd/api/method/sql/clause/with/ColumnAliasInFunctionTest.java

Can't choose right package for this test

SQL: column alias in CAST and ROW_NUMBER functions

---

src/test/java/com/axibase/tsd/api/method/sql/operator/SqlCaseTest.java

SQL: CASE expression #3421

---

src/test/java/com/axibase/tsd/api/method/sql/clause/groupby/GroupByNullTagValue.java

SQL: ORDER BY tag name failure #4028

---

src/test/java/com/axibase/tsd/api/method/entity/EntityRecreateTest.java
src/test/java/com/axibase/tsd/api/method/sql/EntityRecreateTest.java

Need advices for class name and package

SQL: duplicate rows in grouped query

---

src/test/java/com/axibase/tsd/api/method/sql/clause/where/WhereInMetricsTest.java

Can you suggest additional test cases?

Tests for `metrics()`

---

pom.xml
src/main/java/com/axibase/tsd/api/method/replacementtable/ReplacementTableMethod.java
src/main/java/com/axibase/tsd/api/model/replacementtable/ReplacementTable.java
src/main/java/com/axibase/tsd/api/util/Registry.java

replacement table tuned for new Registry functionality

New replacement table registration

---

src/test/java/com/axibase/tsd/api/method/sql/clause/select/Select1Test.java
src/test/java/com/axibase/tsd/api/method/sql/clause/select/SelectOneTest.java

SQL: SELECT 1 not working properly #4067

---

src/main/java/com/axibase/tsd/api/method/extended/CommandMethod.java
src/test/java/com/axibase/tsd/api/method/command/CompressedPayloadTest.java
src/test/java/com/axibase/tsd/api/util/TestUtil.java

Java API client: support gzip compression for content #4192

---

src/test/java/com/axibase/tsd/api/method/sql/clause/where/ThreeValuedLogicTest.java

SQL: Change logic rules according to three-valued logic #4286

---

CONTRIBUTING.md
pom.xml
src/main/java/com/axibase/tsd/api/method/sql/SqlMetaMethod.java
src/main/java/com/axibase/tsd/api/model/sql/ColumnMetaData.java
src/main/java/com/axibase/tsd/api/model/sql/SqlTableParser.java
src/main/java/com/axibase/tsd/api/model/sql/StrOrObjectDeserializer.java
src/main/java/com/axibase/tsd/api/model/sql/StringObjectDeserializer.java
src/main/java/com/axibase/tsd/api/model/sql/StringTable.java
src/main/java/com/axibase/tsd/api/model/sql/StringTableDeserializer.java
src/main/java/com/axibase/tsd/api/model/sql/TableMetaData.java
src/main/java/com/axibase/tsd/api/model/sql/TableMetaDataDeserializer.java
src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java

Separate metadata from tables, add support for /api/sql/meta method

Change meta

---

src/main/java/com/axibase/tsd/api/model/command/SeriesCommand.java
src/test/java/com/axibase/tsd/api/extended/CommandMethodTest.java
src/test/java/com/axibase/tsd/api/method/series/command/AppendFieldTest.java

Network API: append tests #3796 + #3874 + #3885 + #3902

---

src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSubqueryTest.java

* New error message for self-join
* Negatives dates are allowed in subquery
* Disable message stats query tests

Update tests for HBase 1.2.5

---

pom.xml
src/test/resources/logback.xml

Removed `jersey 1` dependency (jersey 2 is used)
Added `allure-java-commons` dependency for Issue annotation.

pom.xml fixes

---

src/test/java/com/axibase/tsd/api/method/sql/clause/where/SqlMerticTagsTest.java

Fixed suggestions from PR https://github.com/axibase/atsd-api-test/pull/339

Added tests description for #4180

---

src/main/java/com/axibase/tsd/api/method/MethodParameters.java
src/main/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/main/java/com/axibase/tsd/api/model/entity/Entity.java
src/main/java/com/axibase/tsd/api/model/metric/Metric.java
src/main/java/com/axibase/tsd/api/model/series/SeriesSearchQuery.java
src/main/java/com/axibase/tsd/api/model/series/SeriesSearchResult.java
src/main/java/com/axibase/tsd/api/model/series/SeriesSearchResultRecord.java
src/main/java/com/axibase/tsd/api/model/series/SeriesSearchResultRecordDeserializer.java
src/test/java/com/axibase/tsd/api/method/series/SeriesSearchTest.java

Please review series search api before I will use it in tests

Series Search api for #4404

---

src/test/java/com/axibase/tsd/api/method/sql/operator/SqlNotEqualsOperatorTest.java

Enabled failing tests after fix https://apps.axibase.com/redmine/issues/4554#note-5

SQL: Change behavior of "datetime !=" operator #4554

---

src/test/java/com/axibase/tsd/api/method/series/command/BackslashCharEscapeTest.java
src/test/java/com/axibase/tsd/api/method/series/command/DoubleBackslashCharEscapeTest.java

Tests disabled until #4662 is being fixed

Fixed failing test

---

src/main/java/com/axibase/tsd/api/method/metric/MetricMethod.java
src/test/java/com/axibase/tsd/api/method/series/SeriesSearchTest.java

Refactoring test for #4044

---

src/test/java/com/axibase/tsd/api/method/sql/SqlTest.java
src/test/java/com/axibase/tsd/api/method/sql/syntax/SqlSubqueryTest.java

SQL: Сolumn name sensitivity in subqueries #5139

---

pom.xml
src/main/java/com/axibase/tsd/api/method/BaseMethod.java

I will commit changes to this branch to check if tests pass on Travis until the build is fixed

Don't return client to pool after exception [DON'T MERGE]

---

pom.xml
src/main/java/com/axibase/tsd/api/method/BaseMethod.java

I will commit changes to this branch to check if tests pass on Travis until the build is fixed

raipc experiments [DON'T MERGE YET]

---

src/test/java/com/axibase/tsd/api/method/sql/function/interpolate/FullInterpolationTest.java

SQL: Interpolation previous with fill=false #4814

---

src/main/java/com/axibase/tsd/logging/LoggingFilter.java

Improved inputStream reading. If content length is greater than 8 Kb, it won't be prettified, and JsonException won't be logged because of invalid (not full) JSON.

fixed logging filter

---

src/main/java/com/axibase/tsd/api/model/series/Sample.java
src/main/java/com/axibase/tsd/api/model/series/Series.java
src/test/java/com/axibase/tsd/api/method/sql/clause/with/SqlWithTimezoneTest.java

I know, these tests are quite simple.
I just wanted to show, that work in progress and let anybody express the opinion.

5542: Add WITH TIMEZONE tests

---

CONTRIBUTING.md

missing space in the header of `CONTRIBUTING.md`

missing space in header of CONTRIBUTING.md

---

src/main/java/com/axibase/tsd/api/method/message/MessageMethod.java
src/main/java/com/axibase/tsd/api/model/command/AbstractCommand.java
src/main/java/com/axibase/tsd/api/model/command/EntityCommand.java
src/main/java/com/axibase/tsd/api/model/command/FieldFormat.java
src/main/java/com/axibase/tsd/api/model/command/MessageCommand.java
src/main/java/com/axibase/tsd/api/model/command/MetricCommand.java
src/main/java/com/axibase/tsd/api/model/command/PropertyCommand.java
src/main/java/com/axibase/tsd/api/model/command/SeriesCommand.java
src/test/java/com/axibase/tsd/api/method/message/MessageInsertTest.java
src/test/java/com/axibase/tsd/api/method/message/command/LengthTest.java
src/test/java/com/axibase/tsd/api/method/property/command/LengthTest.java

PlainCommand refactoring

---

src/main/java/com/axibase/tsd/api/transport/tcp/TCPSender.java
src/test/java/com/axibase/tsd/api/method/property/PropertyTest.java
src/test/java/com/axibase/tsd/api/method/series/command/LineBreakInsideSeriesCommandTest.java
src/test/java/com/axibase/tsd/api/method/sql/response/SqlLargeDataTest.java

Set TCP client timeout to 30 seconds

---

CONTRIBUTING.md
STYLEGUIDE.md

#537 Please, review the style guide and suggest rules/improvements

Style guide

---

pom.xml
src/main/java/com/axibase/tsd/api/Checker.java
src/main/java/com/axibase/tsd/api/method/BaseMethod.java
src/main/java/com/axibase/tsd/logging/LoggingFilter.java
src/test/java/com/axibase/tsd/api/listeners/RequestResponseOnFailWriter.java
src/test/java/com/axibase/tsd/api/method/entity/EntityCommandTest.java
src/test/java/com/axibase/tsd/api/method/series/SeriesQueryTest.java
src/test/resources/logback.xml

Implemented listener to log request and response for failed tests

---

src/test/java/com/axibase/tsd/api/method/sql/function/date/DateFormatMinAndMaxDateTest.java
src/test/java/com/axibase/tsd/api/util/Mocks.java

date_format min and max date tests

---

src/main/java/com/axibase/tsd/logging/LoggingFilter.java

Print headers

---

src/test/java/com/axibase/tsd/api/method/sql/function/date/DateAddTest.java
src/test/java/com/axibase/tsd/api/util/TestUtil.java

Pending for problems with add moths and add quarters to be resolved

Added tests for DATEADD with literal dates

---

src/main/java/com/axibase/tsd/api/method/collections/NamedCollectionMethod.java
src/main/java/com/axibase/tsd/api/method/collections/NamedCollectionsMethod.java
src/main/java/com/axibase/tsd/api/model/collections/NamedCollection.java
src/test/java/com/axibase/tsd/api/method/sql/function/other/SqlCollectionTest.java
src/test/java/com/axibase/tsd/api/util/Mocks.java
src/test/java/com/axibase/tsd/api/util/TestNameGenerator.java

Tests for `collection` function in SQL, Issue 6559

Named collection method, model and tests

---

src/test/java/com/axibase/tsd/api/method/sql/function/aggregate/SlidingTimeWindowTest.java

Pending for 6560#note-11 to be resolved

Added tests for sliding time windows

---

src/main/java/com/axibase/tsd/api/method/checks/TradeCheck.java
src/main/java/com/axibase/tsd/api/model/financial/Trade.java
src/main/java/com/axibase/tsd/api/transport/tcp/TCPTradesSender.java
src/main/java/com/axibase/tsd/api/util/TradeSender.java
src/test/java/com/axibase/tsd/api/method/sql/trade/TradeInstrumentInvalidConditionTest.java

SQL test for invalid instrument conditions

---

pom.xml
src/main/java/com/axibase/tsd/api/model/financial/Trade.java
src/main/kotlin/com/axibase/tsd/api/method/trade/TradeExportMethod.kt
src/test/java/com/axibase/tsd/api/util/CommonAssertions.java
src/test/java/com/axibase/tsd/api/util/Mocks.java
src/test/java/com/axibase/tsd/api/util/TestNameGenerator.java
src/test/kotlin/com/axibase/tsd/api/method/trade/export/TradeExportOhlcvTest.kt
src/test/kotlin/com/axibase/tsd/api/method/trade/export/TradeExportRawTest.kt
src/test/kotlin/com/axibase/tsd/util/CSVMatcher.kt

- statistics tests
- csv matcher
- mock for trade_num

GH-664: OHCLV statistic param tests 

---

src/test/kotlin/com/axibase/tsd/api/method/trade/export/TradeExportRawTest.kt

Trades Export: Raw support for microseconds

---

src/main/java/com/axibase/tsd/api/method/metric/MetricMethod.java
src/main/java/com/axibase/tsd/api/method/metric/MetricSeriesParameters.java
src/test/java/com/axibase/tsd/api/method/metric/MetricSeriesDateLimitTest.java
src/test/java/com/axibase/tsd/api/method/metric/MetricSeriesTest.java
src/test/java/com/axibase/tsd/api/method/tokens/TokenMetricTest.java
src/test/kotlin/com/axibase/tsd/api/method/metric/ApiMetricSeriesTest.kt

API: metric series limit test

---

src/main/java/com/axibase/tsd/api/method/series/SeriesMethod.java
src/main/java/com/axibase/tsd/api/model/Period.java
src/main/java/com/axibase/tsd/api/model/TimeUnit.java
src/main/java/com/axibase/tsd/api/model/series/query/transformation/aggregate/AggregationType.java
src/main/java/com/axibase/tsd/api/model/series/query/transformation/group/GroupType.java
src/test/java/com/axibase/tsd/api/method/series/trade/AnotherTradeSideTest.java
src/test/java/com/axibase/tsd/api/method/series/trade/SyntheticDataProvider.java
src/test/java/com/axibase/tsd/api/method/series/trade/ohlcv/OhlcvTest.java
src/test/java/com/axibase/tsd/api/method/series/trade/wvap/VwapTest.java
src/test/java/com/axibase/tsd/api/method/series/trade/wvap/VwapTestCasesBuilder.java
src/test/java/com/axibase/tsd/api/util/CommonAssertions.java

Add `AnotherTradeSideTest` to test series query for aggregated/grouped trades with different trade side requirements.

Test series query trade side.

---

src/main/java/com/axibase/tsd/api/method/BaseMethod.java
src/test/java/com/axibase/tsd/api/method/forecast/ForecastFormTest.java

Run tests sequentially. Increase waiting time.

Try to fix ForecastFormTest.

---

src/test/java/com/axibase/tsd/api/method/financial/InstrumentSearchBase.java
src/test/java/com/axibase/tsd/api/method/financial/InstrumentSearchTest.java

GH-726: ISIN search

---

src/main/java/com/axibase/tsd/api/model/series/Series.java
src/test/java/com/axibase/tsd/api/method/export/VersionedSeriesExportTest.java

Test export series in csv format via the `/export` form. Specifically test export of series versions, i.e. series values with the same timestamp, and text annotations of versioned values.

Test export of versioned series, i.e. series which has several annotated values for some timestamps.  
